# Perceptron 

Verificar se o ser vivo é  quadrupede de ou bípede

•Suposições quanto ao resultadoQuadrúpede = 1           
Bípede = -1

|       Ser Servivo |Vetor                |  Resultado esperado|
|----------|---------------------|--------------------|
|Cão      |[ 1 -1 1  1 ]        |                   1|
|Gato     |[ 1 1  1  1 ]        |                   1|
|Cavalo   |[ 1 1 -1  1 ]        |                   1|
|Homem    |[-1 -1-1  1 ]        |                  -1|
|Galinha  |[-1 1 -1  1 ]        |                  -1|
|Avestruz |[ 1-1  1 -1 ]        |                  -1|

In [ ]:
# Dados iniciais
import numpy as np 
# Base de dados

# Classe 1 
sv1 = np.array( [1,-1,1,1] )
sv2 = np.array( [1,1,1,1] )
sv3 = np.array( [1,1,1,1] )

# Classe -1
sv4 = np.array( [-1,-1,-1,1] )
sv5 = np.array( [-1,1,-1,1] )
sv6 = np.array( [1,-1, 1,-1] )

# Pesos iniciais 
Pesos = np.array( [0, 0, 0,0] )

# Taxa de aprendizagem
eta = 0.4 
# Viés 
bias = 0.5  

In [ ]:
# Função para a soma ponderada 
# u = x0*w0 +  x1*w1 + x2*w2 -1*θ 
# m = x0*w0 +  x1*w1 + x2*w2
# u = m -1*θ
def somaPonderada(X,W):
  bias = 0.5 
  m = np.multiply(X,W)
  u = np.sum(m) -1*bias
  return u 

In [ ]:
# Função de ativação 
# Função Degrau 
def funcaoAtivacao(u):
  if u >= 0:
    return 1
  else:
    return -1

In [ ]:
# Função de saída 
def saida(X,W):
  u = somaPonderada(X,W)
  return funcaoAtivacao(u) 


In [ ]:
# Função para ajustes dos pesos
# Parte cententral do processo de aprendizagem 
# novo wi  →  wi = wi +  η xi (d - y ) 
def ajustaPesos(eta,W,X,bias,d,y):
  e = d - y 
  novoW = W + eta*X*e
  novoB = bias + eta*(-1)*e 
  return novoW, novoB  


# Treinamento 
* Realizado manualmente para ilustrar o processo 
* Aprsenta uma entrada e calcula a saída de maneira iterativa 

## Iteração 1

In [ ]:
# ser vivo 1 -> 1 
d = 1 
sv1 = saida(sv1,Pesos) 
print(y)
# Ajuste dos pesos 
Pesos,bias = ajustaPesos(eta,Pesos,sv1,bias,d,y) 
print(Pesos)
print(bias)  

# ser vivo 2 -> 1 
d = 1 
sv1 = saida(sv2,Pesos) 
print(y)
# Ajuste dos pesos 
Pesos,bias = ajustaPesos(eta,Pesos,sv2,bias,d,y) 
print(Pesos)
print(bias)

# ser vivo 3 -> 1 
d = 1 
sv1 = saida(sv3,Pesos) 
print(y)
# Ajuste dos pesos 
Pesos,bias = ajustaPesos(eta,Pesos,sv3,bias,d,y) 
print(Pesos)
print(bias) 

# ser vivo 4 -> -1 
d = -1 
sv1 = saida(sv4,Pesos) 
print(y)
# Ajuste dos pesos 
Pesos,bias = ajustaPesos(eta,Pesos,sv4,bias,d,y) 
print(Pesos)
print(bias) 

# ser vivo 5 -> -1 
d = -1 
sv1 = saida(sv5,Pesos) 
print(y)
# Ajuste dos pesos 
Pesos,bias = ajustaPesos(eta,Pesos,sv5,bias,d,y) 
print(Pesos)
print(bias)

# ser vivo 6 -> -1 
d = -1 
sv1 = saida(sv6,Pesos) 
print(y)
# Ajuste dos pesos 
Pesos,bias = ajustaPesos(eta,Pesos,sv6,bias,d,y) 
print(Pesos)
print(bias)



1
[6.4 6.4 6.4 3.2]
10.100000000000001
1
[6.4 6.4 6.4 3.2]
10.100000000000001
1
[6.4 6.4 6.4 3.2]
10.100000000000001
1
[7.2 7.2 7.2 2.4]
10.900000000000002
1
[8.  6.4 8.  1.6]
11.700000000000003
1
[7.2 7.2 7.2 2.4]
12.500000000000004


## Iteração 2

In [ ]:
# ser vivo 1 -> 1 
d = 1 
sv1 = saida(sv1,Pesos) 
print(y)
# Ajuste dos pesos 
Pesos,bias = ajustaPesos(eta,Pesos,sv1,bias,d,y) 
print(Pesos)
print(bias) 

# ser vivo 2 -> 1 
d = 1 
sv1 = saida(sv2,Pesos) 
print(y)
# Ajuste dos pesos 
Pesos,bias = ajustaPesos(eta,Pesos,sv2,bias,d,y) 
print(Pesos)
print(bias)

# ser vivo 3 -> 1 
d = 1 
sv1 = saida(sv3,Pesos) 
print(y)
# Ajuste dos pesos 
Pesos,bias = ajustaPesos(eta,Pesos,sv3,bias,d,y) 
print(Pesos)
print(bias) 


# ser vivo 4 -> -1 
d = -1 
sv1 = saida(sv4,Pesos) 
print(y)
# Ajuste dos pesos 
Pesos,bias = ajustaPesos(eta,Pesos,sv4,bias,d,y) 
print(Pesos)
print(bias) 

# ser vivo 5 -> -1 
d = -1 
sv1 = saida(sv5,Pesos) 
print(y)
# Ajuste dos pesos 
Pesos,bias = ajustaPesos(eta,Pesos,sv5,bias,d,y) 
print(Pesos)
print(bias)

# ser vivo 6 -> -1 
d = -1 
sv1 = saida(sv6,Pesos) 
print(y)
# Ajuste dos pesos 
Pesos,bias = ajustaPesos(eta,Pesos,sv6,bias,d,y) 
print(Pesos)
print(bias)

1
[7.2 7.2 7.2 2.4]
12.500000000000004
1
[7.2 7.2 7.2 2.4]
12.500000000000004
1
[7.2 7.2 7.2 2.4]
12.500000000000004
1
[8.  8.  8.  1.6]
13.300000000000004
1
[8.8 7.2 8.8 0.8]
14.100000000000005
1
[8.  8.  8.  1.6]
14.900000000000006


# Teste
* A que classe pertencem os padrões 111, 000, 100 e 011?

In [ ]:
# testar gato 1111 quadrupede 1
T = np.array([1, 1, 1,1]) 
print("Saida para ",T," é ", saida(T,Pesos))

Saida para  [1 1 1 1]  é  1


In [ ]:
# testar homem -1 -1-1 1 bipede -1
T = np.array([-1, -1, -1,1]) 
print("Saida para ",T," é ", saida(T,Pesos))

Saida para  [-1 -1 -1  1]  é  -1
